# Change these first
owner: AykhanUV # Your GitHub organization or username, where this repository lives
repo: pingus # The name of this repository
user-agent: AykhanUV

sites:
  - name: Replit Dev Site # You can change this name if you like
    url: https://65617f0c-04f8-4ac2-9cf4-616a91cc8d35-00-dof3ck9k3e8w.pike.replit.dev/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org # Removed
  baseUrl: /pingus # Set for GitHub Pages
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AykhanUV Status Page # Updated name
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub." # Kept default
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime) # Kept default
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO # This will be dynamically replaced by Upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
